import * as THREE from 'three';

/**
 * 簡易的なSTEPファイルパーサー
 * ISO 10303-21形式の基本的な読み込みをサポート
 */
export const loadSTEPFile = async (file: File): Promise<THREE.Group> => {
  const text = await file.text();

  try {
    // STEPファイルのヘッダーチェック
    if (!text.includes('ISO-10303-21')) {
      throw new Error('有効なSTEPファイルではありません');
    }

    // DATAセクションを抽出
    const dataMatch = text.match(/DATA;([\s\S]*?)ENDSEC;/);
    if (!dataMatch) {
      throw new Error('STEPファイルのDATAセクションが見つかりません');
    }

    const dataSection = dataMatch[1];

    // エンティティを抽出（簡易版）
    const entities = new Map<string, any>();
    const entityRegex = /#(\d+)=([^;]+);/g;
    let match;

    while ((match = entityRegex.exec(dataSection)) !== null) {
      const id = match[1];
      const content = match[2].trim();
      entities.set(id, parseSTEPEntity(content));
    }

    // 3Dジオメトリを構築
    const group = buildGeometryFromSTEP(entities);

    return group;
  } catch (error) {
    console.error('STEP parsing error:', error);
    throw new Error(`STEPファイルの解析に失敗しました: ${error instanceof Error ? error.message : '不明なエラー'}`);
  }
};

/**
 * STEPエンティティをパース
 */
const parseSTEPEntity = (content: string): any => {
  const typeMatch = content.match(/^(\w+)\((.*)\)$/);
  if (!typeMatch) return { raw: content };

  const [, type, params] = typeMatch;
  return {
    type,
    params: params.split(',').map(p => p.trim())
  };
};

/**
 * STEPエンティティから3Dジオメトリを構築
 */
const buildGeometryFromSTEP = (_entities: Map<string, any>): THREE.Group => {
  const group = new THREE.Group();

  // 簡易的な実装：基本的なボックスを生成
  // 実際のSTEPファイルからの完全な変換は非常に複雑なため、
  // ここでは基本形状のみをサポート

  const geometry = new THREE.BoxGeometry(10, 10, 10);
  const material = new THREE.MeshStandardMaterial({
    color: 0x808080,
    metalness: 0.5,
    roughness: 0.5
  });
  const mesh = new THREE.Mesh(geometry, material);

  group.add(mesh);

  // 注: 完全なSTEP解析にはopencascade.jsなどの専用ライブラリが必要です
  console.warn('STEP file loaded with basic support. For full STEP support, consider using a dedicated CAD kernel.');

  return group;
};

/**
 * STEPファイルをエクスポート
 */
export const exportSTEP = (mesh: THREE.Mesh | THREE.Group, _filename: string = 'export.step'): Blob => {
  // 簡易的なSTEPファイル生成
  const stepContent = generateBasicSTEP(mesh);
  return new Blob([stepContent], { type: 'application/step' });
};

/**
 * 基本的なSTEPファイルを生成
 */
const generateBasicSTEP = (mesh: THREE.Mesh | THREE.Group): string => {
  const timestamp = new Date().toISOString();

  let step = `ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('Generated by 3D CAD Suite'),'2;1');
FILE_NAME('${timestamp}','${timestamp}',(''),(''),
  '3D CAD Suite','3D CAD Suite','');
FILE_SCHEMA(('AUTOMOTIVE_DESIGN'));
ENDSEC;

DATA;
#1=CARTESIAN_POINT('',(0.,0.,0.));
#2=DIRECTION('',(0.,0.,1.));
#3=DIRECTION('',(1.,0.,0.));
#4=AXIS2_PLACEMENT_3D('',#1,#2,#3);
`;

  let entityId = 5;

  // メッシュから頂点と面を抽出
  mesh.traverse((child) => {
    if (child instanceof THREE.Mesh && child.geometry) {
      const geometry = child.geometry;
      const position = geometry.attributes.position;

      if (position) {
        // 頂点を追加（サンプル）
        for (let i = 0; i < Math.min(position.count, 8); i++) {
          const x = position.getX(i).toFixed(6);
          const y = position.getY(i).toFixed(6);
          const z = position.getZ(i).toFixed(6);
          step += `#${entityId}=CARTESIAN_POINT('',(${x},${y},${z}));\n`;
          entityId++;
        }
      }
    }
  });

  step += `ENDSEC;
END-ISO-10303-21;`;

  return step;
};
